import { builtinModules } from 'node:module';
import process from 'node:process';
import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	// Obsidian ships these at runtime; bundling them would break the plugin.
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// Both spellings: esbuild treats "node:fs" as a different specifier from
		// "fs", and builtinModules only lists the bare names.
		...builtinModules,
		...builtinModules.map((name) => `node:${name}`),
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
